hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 1024
  max_response_length: 1024
  train_batch_size: 256
  return_raw_chat: True
  shuffle: False

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_assistant_turns: 2
      format: qwen
      final_summary: True
      summary_prompt: "You have reached the maximum number of interaction turns. Please provide your final answer directly using the <answer></answer> tags."
