### model
model_name_or_path: ./outputs/Qwen-Merge-VL-4B-stage2.2
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: false
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: text2image,image_thinking
template: qwen_merge_vl
cutoff_len: 8096
overwrite_cache: true
preprocessing_num_workers: 64
dataloader_num_workers: 64
tokenized_path: save/4b_pt_stage3_tokenized

### output
output_dir: ./outputs/Qwen-Merge-VL-4B-stage3
logging_steps: 1
save_steps: 200
save_total_limit: 10
save_strategy: 'steps'
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: Qwen-Merge-VL-4B-stage3

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 1.2
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
